### ISSUE TITLE
Pre training file not found

### ISSUE THREAD

**Issue by shaozifly** [joycenerd/Deep_Learning_Practice_labs#1]
/checkpoints/resnet50/relu_0.001_0.7335.pt， 'resnet50_pretrained':'./checkpoints/best/resnet50_pretrained.pt',
'resnet50':'./checkpoints/best/resnet50.pt',
'resnet18_pretrained':'./checkpoints/best/resnet18_pretrained.pt',
'resnet18':'./checkpoints/best/resnet18.pt',
These documents are not available. There is no way to train。

**Comment by zhiyichin** [comment]
Hi, the checkpoints are not provided because I'm afraid other students in NYCU who also registered in this course will copy the whole homework. Also, I don't have the checkpoints currently because I have done this project a couple of months ago, and all the data has been deleted from my local computer.
